### ISSUE TITLE
Spec Improvements

### ISSUE THREAD

**Issue by andreaSimonePorceddu** [VLK-STUDIO/morfeo#109]
This is a proposal to improve the default slice interfaces in order to have a more scalable system and a more intuitive theme building.

## Sizes

The `xxs` and `xxl` could become  `2xs` and `2xl` in order to suggest a more scalable naming for all sizes props.
 
## Font Slice

As the font slice keys could be used to define different fonts and even the same fonts with different weights and styles it could be better to leave this slice more flexible by changing `regular, medium, bold` to just one default property `default`.

## Borders

`primary` and `secondary` keys seem to not work properly to define `borders`. We could change them with some more appropriate like `thin` and `bold.

## Zindices

`light, soft and strong` keys seem to not work properly to define `zIndices`. We could change them with some more appropriate like `lowest, lower, low, high, higher, highest.

**Comment by mauroerta** [comment]
I agree with the new interfaces, steps needed if we want to change those interfaces are:
 - update @morfeo/spec package
 - update @morfeo/preset-default
 - re-build the theme and update css inside the web-extension
 - update the docs
Will you do it?

**Comment by andreaSimonePorceddu** [comment]
closed with PR #110

**Comment by andreaSimonePorceddu** [comment]
closed with PR #110
